services:

  postgres_db:
    container_name: postgres_test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=contrasena
      - POSTGRES_DATABASE=test
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - bosonit-network

networks:
  bosonit-network:
    driver: bridge


